title: Rosa Choq
email: rosildalino@hotmail.com
description: Tudo sobre produtos, vendas e como ser uma representante Avon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rosachoq.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/sass
  style: compressed

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
